---
- name: Playbook for metric beat
  hosts: webservers
  become: true
  tasks:
          - name: download metric beat deb file
            command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

          - name: install deb file
            command: dpkg -i metricbeat-7.4.0-amd64.deb

          - name: copy the configuration file
            copy:
                    src: /etc/ansible/metricbeat-config.yml
                    dest: /etc/metricbeat/metricbeat.yml

          - name: enable metric beat module
            command: metricbeat modules enable system

          - name: setup metricbeat
            command: metricbeat setup

          - name: emable metricbeat on start
            service:
                    name: metricbeat
                    state: started
                    enabled: yes
