---
- name: Configure Web Servers
  hosts: webservers
  become: yes
  tasks:
          - name: Install python3-pip
            apt:
                    force_apt_get: yes
                    name: python3-pip
                    state: present
                    update_cache: yes

          - name: Install docker.io
            apt:
                    name: docker.io
                    state: present

          - name: Install docker via pip
            pip:
                    name: docker
                    state: present

          - name: pull an image
            docker_container:
                    name: dvwa
                    image: cyberxsecurity/dvwa
                    state: started
                    restart_policy: always
                    published_ports: 80:80

          - name: Start docker service
            systemd:
                    name: "docker"
                    state: started
                    enabled: yes


